version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
      target: runner
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_PATH: /app/data/stationery.sqlite
      DATABASE_URL: /app/data/stationery.sqlite
    ports:
      - "8080:8080"
    volumes:
      - db_data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
      target: runner
    environment:
      NODE_ENV: production
    ports:
      - "8081:80"
      - "5173:80"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  db_data:
    name: stationery_db_data
