name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'true'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2 libffi8 libx264-dev
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Set Playwright Chromium path
        run: echo "PUPPETEER_EXECUTABLE_PATH=$(find ~/.cache/ms-playwright -name chrome -type f | head -n 1)" >> $GITHUB_ENV
      - name: Run unit tests
        run: pnpm test
      - name: Run end-to-end tests
        run: pnpm e2e
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: warn
